#!/bin/bash
# This file contains a list of variables as sourced in the deployment wrapper scripts
# <component>_RELEASE corresponds to the version of a component such as UI or API
# installed in the virtual appliance
# RELEASE numbers have to be compatible with this verision of the appliance stack
#

# Versions of virtual appliance components
APPLIANCE_VERSION='4.0.0-a0'
UI_RELEASE='v7.3.2'
#API_RELEASE='v5.33.5' # not ready yet
API_RELEASE='master'
NCBO_CRON_RELEASE='5.33.4'
ONTOLOGIES_LINKED_DATA_RELEASE='v5.33.4'
