#!/bin/bash
# This file contains a list of variables as sourced in the deployment wrapper scripts
# <component>_RELEASE corresponds to the version of a component such as UI or API
# installed in the virtual appliance
# RELEASE numbers have to be compatible with this verision of the appliance stack
#

# Versions of virtual appliance components
APPLIANCE_VERSION='4.0.0'
UI_RELEASE='v8.1.0'
API_RELEASE='v6.1.0'
NCBO_CRON_RELEASE='v6.1.0'
ONTOLOGIES_LINKED_DATA_RELEASE='v6.1.0'
