#!/bin/bash
# This file contains a list of variables as sourced in the deployment wrapper scripts
# <component>_RELEASE corresponds to the version of a component such as UI or API
# installed in the virtual appliance
# RELEASE numbers have to be compatible with this verision of the appliance stack
#

# Versions of virtual appliance components
APPLIANCE_VERSION=3.0rc1
API_RELEASE=v5.13.0
UI_RELEASE=v5.7.0
NCBO_CRON_RELEASE=v5.13.0
ONTOLOGIES_LINKED_DATA_RELEASE=$API_RELEASE

# general settings
VIRTUAL_APPLIANCE_REPO=/srv/ncbo/virtual_appliance
#export LOCAL_CONFIG_PATH=$VIRTUAL_APPLIANCE_REPO/appliance_config
