#!/bin/bash
# Script to start OntoPortal stack

services='
agraph.service
tomcat.service
redis-server-goo_cache.service
redis-server-http_cache.service
redis-server-persistent.service
mgrep.service
memcached.service
solr.service
ncbo_cron.service
unicorn.service
ui.service
nginx.service
'
for service in $services; do
  /bin/systemctl start $service
done
