#!/bin/bash
# Script to restart OntoPortal stack

services='
ncbo_cron.service
httpd.service
nginx.service
unicorn.service
memcached.service
redis-server-goo.service
redis-server-http.service
redis-server-presistent.service
mgrep.service
solr.service
tomcat.service
4s-httpd.service
4s-backend.service
4s-boss.service
'

for service in $services; do
  /bin/systemctl stop $service
done
