#!/bin/bash
# Ontoportal daemon servides status

TERM=linux

services='
4s-boss.service
4s-backend.service
4s-httpd.service
tomcat.service
redis-server-goo_cache.service
redis-server-http_cache.service
redis-server-persistent.service
mgrep.service
memcached.service
solr.service
ncbo_cron.service
unicorn.service
nginx.service
httpd.service
'

NC=$(tput sgr0)
RED=$(tput setaf 1)
GRN=$(tput setaf 2)
VERBOSE=false


while getopts "v" Option
  do
   case $Option in
     v )
       VERBOSE=true
     ;;
   esac
done
if $VERBOSE; then
  echo "SOLR status:"
  curl "http://localhost:8983/solr/admin/cores?action=STATUS"
  echo "4store status:"
  4s-admin list-stores
  curl "http://localhost:8081/status/"
fi

for service in $services; do
  isactive=$(/bin/systemctl is-active $service)
  STATUS=$((STATUS + $?))
  if [[ "$isactive" == 'active' ]]; then
     COLOR=$GRN
  else
     COLOR=$RED
  fi
  printf "%*s %b\n" -35 "${service}" "${COLOR}${isactive}${NC}"
done
exit $STATUS

