#!/bin/bash
# Script to restart OntoPortal stack

services='
4s-boss.service
4s-backend.service
4s-httpd.service
tomcat.service
redis-server-goo.service
redis-server-http.service
redis-server-presistent.service
mgrep.service
memcached.service
solr.service
ncbo_cron.service
unicorn.service
nginx.service
httpd.service
'
for service in $services; do
  /bin/systemctl start $service
done
