#!/bin/bash
# Script to restart OntoPortal stack
if (( $EUID != 0 )); then
    echo "Please run with \"sudo $0\""
    exit
fi
services='
ncbo_cron.service
nginx.service
ui.service
unicorn.service
memcached.service
redis-server-goo_cache.service
redis-server-http_cache.service
redis-server-persistent.service
mgrep.service
solr.service
tomcat.service
agraph.service
'

for service in $services; do
  /bin/systemctl stop $service
done
